version: '3.2'

services:
  web: &default
    build:
      context: .
    ports:
      - 3006:3006
    volumes:
      - .:/app
      - bundle:/bundle
    command: bundle exec rails s -p 3006 -b '0.0.0.0'
    depends_on:
      - db
    links:
      - db
    external_links:
      - app
    networks:
      - default
      - communication_network
    healthcheck:
      test: curl -f http://localhost:3006 || exit 1
      retries: 3

  karafka:
    <<: *default
    ports: []
    command: bin/karafka server
    links:
      - kafka
    external_links: []
    healthcheck:
      disable: true

  db:
    image: postgres:13.3
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - default
      - communication_network

volumes:
  bundle:
  postgres:

networks:
  communication_network:
    external: true
